#
# Запуск запроса на выполнение Ctrl+Shift+O
# Ctrl+Alt+H
#
@host = localhost:3000
# @host = 192.168.88.254:3000
@login = 1
@password = 1

# Тип сообщения
@messageType = 50


### Health check
GET http://{{host}}/health


### Генерация IRIS сообщения типа messageType
# @name newIrisMessage
GET http://{{host}}/api/v1/message/{{messageType}}/iris


### Обработка IRIS XML сообщения
@processedIrisMessage = {{newIrisMessage.response.body.*}}
POST http://{{host}}/api/v1/message/iris
Content-Type: text/xml
Debug-Mode: true

{{processedIrisMessage}}


### Обработка IRIS XML сообщения
POST http://{{host}}/api/v1/message/iris
Content-Type: text/xml
Debug-Mode: true

<IRIS Version="2" Message="ModelRequest" MessageTypeId="1" MessageId="33231243" custom="test">
  <id>d6b40af9c2929f8068f0eae2</id>
  <amount>6513363</amount>
  <dt>2025-09-16 13:55:44</dt>
  <f1>"1234567890"</f1>
  <f2>value1</f2>
  <f3>1</f3>
  <f4>"1234567890"</f4>
  <f5>"1234567890"</f5>
  <f6>"1234567890"</f6>
  <f12>"1234567890"</f12>
  <f20>"1234567890"</f20>
  <f21>"1234567890"</f21>
  <f22>"1234567890"</f22>
</IRIS>


### Обработка IRIS XML сообщения
POST http://{{host}}/api/v1/message/iris
Content-Type: text/xml
Debug-Mode: false

<IRIS Version="1" Message="ModelRequest" MessageTypeId="50" MessageId="3323124" custom="test">
	<i000>0100</i000>
	<fmt>R</fmt>
	<src>RNP</src>
	<aserno>123123123</aserno>
	<mtrtyp>3</mtrtyp>
	<i003>00</i003>
	<tstamp>2024-12-15 02:59:59</tstamp>
	<i002>22007011111111</i002>
	<SysSrc>15</SysSrc>
	<card_present>false</card_present>
	<i055_offline_sum>0</i055_offline_sum>
	<i055_offline_cnt>0</i055_offline_cnt>
	<i052>N</i052>
	<i006>836.00</i006>
	<eci>N</eci>
	<pinok>0</pinok>
	<no_cvm_vuln>0</no_cvm_vuln>
	<used_signature>0</used_signature>
	<otbAffGrp>7145.28</otbAffGrp>
	<otbAllGrp>7145.28</otbAllGrp>
	<cnt>643</cnt>
	<oac>836.00</oac>
	<agreement>5375191510</agreement>
	<chipTerminal>N</chipTerminal>
	<ssnumber>7-3NEP2IV2J1</ssnumber>
	<mtrspc>0</mtrspc>
	<inn>312329558051</inn>
	<i004>836.00</i004>
	<i011>233423</i011>
	<i014>3401</i014>
	<i018>5814</i018>
	<i022>81</i022>
	<i032>123232</i032>
	<i037>12312312</i037>
	<i041>123123123</i041>
	<i042>12312</i042>
	<i043a>DODO PIZZA test</i043a>
	<i043b>Pizzario, test</i043b>
	<i025>as</i025>
	<cardNumber>2200000000000111111111111111111000</cardNumber>
    <i048>^17280000000000000000000000000000000000000000^320c312329558051^09013</i048>	
	<i049>643</i049>
	<ucid>1121120922</ucid>
    <cd_sign>D</cd_sign>
    <is_financial>Y</is_financial>
    <sme_flag>false</sme_flag>
    <pin_flag>false</pin_flag>
    <token_flag>false</token_flag>
</IRIS>


### Тест исправления дублирования атрибутов в XML (MessageTypeId и MessageId)
POST http://{{host}}/api/v1/message/iris
Content-Type: text/xml
Debug-Mode: true

<IRIS Version="1" Message="ModelRequest" MessageTypeId="34" MessageId="3323123" custom="test">
<MessageTypeId>1000</MessageTypeId>
<MessageId>2222</MessageId>
</IRIS>


### Генерация JSON сообщения типа messageType
# @name newMessage
GET http://{{host}}/api/v1/message/{{messageType}}/json

### Обработка сообщения типа messageType
@processedMessage = {{newMessage.response.body.$}}
POST http://{{host}}/api/v1/message/{{messageType}}/json
Content-Type: application/json
Debug-Mode: false

{{processedMessage}}


### Обработка тестового сообщения типа messageType
POST http://{{host}}/api/v1/message/{{messageType}}/json
Content-Type: application/json
Debug-Mode: true

{
  "id": "2bc902747112fdf768e81748",
  "messageTypeId": {{messageType}},
  "amount": 3113715,
  "dt": "2025-06-10T13:12:31.695Z",
  "f1": "1234567890",
  "f2": "value1",
  "f3": 2,
  "f4": "1234567890",
  "f5": "1234567890",
  "f6": "1234567890",
  "f12": "1234567890",
  "f20": "1234567890",
  "f21": "1234567890",
  "f22": "1234567890"
}


### Обработка сообщения типа 1
POST http://{{host}}/api/v1/message/1/json
Content-Type: application/json

{
    "MessageId": "1e2f63841e9fbea668e68832",
    "acc_identification_flag": 1000,
    "acc_prepaid": false,
    "agreement": 1000,
    "custom_auth_limit": 1000,
    "dst_client_id": "ZQhYClA",
    "fid_md": 1000,
    "from_ros": 8579521,
    "grade": 92791,
    "inn": "PbpMhelLISNEv",
    "INN_recepient": "AufzrzfAwc",
    "insurance_activity": 9336780,
    "ip_address": "AWbCdqHJZFj",
    "kir_flg": 1000,
    "md_agreement_rosbank_flag": 5784330,
    "md_fid01": 1000,
    "md_fid01.2": 1504285,
    "md_fid02": 5760850,
    "md_fid02.2": 2202780,
    "md_fid03": 7484933,
    "md_fid04": 8633290,
    "md_fid08.1": 2025269,
    "md_fid08.2": 1000,
    "md_fid08.3": 9591313,
    "md_fid09": 1007326,
    "md_fid10": 3745525,
    "md_fid11": 3053738,
    "md_fid15": 986823,
    "md_fid15.2": 3947106,
    "md_fid16": 3878886,
    "md_fid16.2": 7593227,
    "md_rosbank_userAgent": "11111111111111111111",
    "monthly_limit": 1126849,
    "msgMode": "BygSfxSuugyBocfX",
    "organization_id": "OhWVZYyyPRF",
    "p_dstCardNumber": "HJv",
    "p_dstClientId": "fyotHYtGHFYfEhUqHIHBwZ",
    "p_dstOrganisationID": "YqybHOxIhzIRfpqbk",
    "pan": "ApaxoNCp",
    "PAN": "APxmCkSAGgLz",
    "pe_aml_status": 4801163,
    "pe_birthdate_dst": "2024-10-10T11:35:40.753Z",
    "pe_child_flag": 3823825,
    "pe_drop_flag": 8423561,
    "pe_dst_aml_status": 1978279,
    "pe_parent_flag": 3616571,
    "pe_phone_dst": "kNEmy",
    "pe_pm_client_id": "aHOjhGmYOVv",
    "pe_pm_flag_num": 4287917,
    "pe_rosbank_private_flag": 5292035,
    "pe_vip_flag_2_phone": 7153399,
    "ph_segment": 4078799,
    "phone": "dOgIp",
    "receiver_acc_and_bik": "bijyty",
    "rosbank_risk_flag1": 4914738,
    "rosbank_risk_flag2": 8833656,
    "rosbank_risk_flag3": 52819,
    "s_client_id": "eFxpEYeilSTZtjWEk",
    "s_organization_id": "FkRFJIAElZlyw",
    "subscription": 5095931,
    "subscription_date": "2024-07-22T06:20:28.636Z",
    "sum_credlimit": 6760985,
    "timestamp": "2024-09-26T14:18:25.203Z",
    "vul_flg": true
}




### Обработка тестового сообщения типа 50
POST http://{{host}}/api/v1/message/50/json
Content-Type: application/json

{
  "MessageTypeID": 50,
  "Timestamp": "2025-10-19T18:42:25.701Z",
  "payment_id": "12345678901234567895",
  "fmt": "A",
  "rul": "atm88.1",
  "ssnumber": "12345678",
  "i039": "00",
  "i022": "0710",
  "dpan": "1234567890123456",
  "agreement": "1234567890",
  "i018": "4814",
  "i002": "1234567890123456",
  "i042": "123456789012345",
  "oac": 5000,
  "p_prv_id": 1,
  "tstamp": "2025-10-19",
  "status": "00",
  "rsncd": "00",
  "i049": "643",
  "i043b": "Moscow",
  "receiverCardNum": "9876543210987654",
  "i043a": "Test Merchant LLC",
  "requestorID": "MobileApp",
  "receiverRequisites": "1234567890123456",
  "ops_source_client_id": "87654321",
  "eci": "05",
  "i003": "000000",
  "i000": "0100",
  "s_authenticationResult": 1,
  "authenticationType": 1,
  "i032": "123456",
  "organization_id": "123456789",
  "i052": "1234",
  "i041": "12345678",
  "otbAffGrp": 1000,
  "servrul": "rule1,rule2",
  "nspk_rulesSet": "Android 12",
  "cnt": "RU",
  "mtrtyp": 1,
  "cavv": "abc123def456",
  "bankacc": "40817810123456789012",
  "status_reverse": "00",
  "mtrmod": 1,
  "phone": "+79001234567",
  "email": "test@example.com",
  "IP": "192.168.1.100",
  "orderId": "ORD123456789",
  "deviceId": "device123456789",
  "userAgent": "Mozilla/5.0 (Android 12; Mobile; rv:91.0)",
  "s_origin": "Card",
  "p_cardtype": "1",
  "p_dstCardType": "1",
  "White_List": "0",
  "Resolution": 1,
  "payType": "1",
  "p_PGinterface": "P2P_PRT",
  "md_issBIN_3NumCntCode": "643",
  "p_basicFieldKey_CRC32": "a1b2c3d4",
  "pe_tb_client_private_flag": false,
  "pe_vip_flag_3": "0",
  "pe_casino_flag_2": "1",
  "md_casino_client_flag_2": "1",
  "Issuing_BIN_8": "12345678",
  "agg_uniqueMerchId": "unique123",
  "PAN_Listing": "1",
  "ap_source_ip_by_client": "192.168.1.100",
  "rebillId": "rebill123",
  "deviceId_CRC32": "device123",
  "p_prvCode": "PRV001",
  "ap_payment_after_tokenization_3h": "1",
  "ap_payment_after_tokenization_not_green_7d": "0",
  "ap_payments_by_token_30_2d_ind": "1",
  "atmRejectedItems": "0",
  "atm_after_activation_lk_3h": "0",
  "atm_after_activation_sr_3h": "0",
  "atm_after_pc_2h": "0",
  "atm_after_pn_2h": "0",
  "atm_attribute": "1",
  "c2c_from_PAN_15m_cnt": "1",
  "c2c_from_PAN_15m_dst": "1",
  "c2c_same_dst_card_and_basicFieldKey": "1",
  "c2c_same_dst_cardnum": "1",
  "c2c_same_recipient": "1",
  "c2c_type": "1",
  "case_from_iris_sme": "0",
  "clientType": "1",
  "confirmationType": "1",
  "confirmed_device_indicator": "1",
  "drop_output_list": "0",
  "exc_merch": "0",
  "exc_providers": "0",
  "exchange_broker": "0",
  "exchange_mobile": "0",
  "exchange_prv_groups": "0",
  "finalTimestamp": "2025-10-19T18:42:25.701Z",
  "i_3ds_fp": "fp123",
  "i_Drunk_places_fraud_merchant_30d": "0",
  "i_PG_same_PAN_dst_200d_2d": "0",
  "i_PG_same_recipient_200_to_2d": "0",
  "i_any_payment_after_bad_drinking_place_24h_indicator_cnt": "0",
  "i_any_payment_after_bad_drinking_place_24h_indicator_sum": "0",
  "i_any_payment_after_drinking_place_9h": "0",
  "i_any_trxn_after_PINCHNG_indicator_3h": "0",
  "i_atm_CO_05_in_kzn_5d_ind": "0",
  "i_atm_after_taxi_5h_ind": "0",
  "i_auths_many_devices_14d_cnt": "0",
  "i_auths_trusted_device_30d": "0",
  "i_auths_trusted_wuid_30d": "0",
  "i_diff_clients_1_device_30d": "0",
  "i_many_clients_from_1_device_30d": "0",
  "i_operation_after_night_bars_3h_cnt": "0",
  "i_operation_after_pc_bad_FP_4h": "0",
  "i_operations_with_PIN_1h": "0",
  "i_pg_auth_after_sr_wb_48h": "0",
  "i_stas_after_bad_drinking_place_24h_ind_cnt": "0",
  "i_stas_after_bad_drinking_place_24h_ind_sum": "0",
  "i_stas_any_trxn_after_PINCHNG_ind_3h": "0",
  "i_stas_payment_after_drinking_place_6h_indicator_sum": "0",
  "i_stas_payment_after_drinking_place_or_shop_8h": "0",
  "i_test_cancel_selfie_by_device_70_trxn_24h": "0",
  "iss_black_listed": "0",
  "kpp": "123456789",
  "localTimestamp": "2025-10-19T18:42:25.701Z",
  "mass3_softDate": "2024-01-01",
  "md_ATM_city": "Moscow",
  "md_ATM_regionCode": "77",
  "md_IPGEO_3NumCntCode": "643",
  "md_IP_proxy_type": "0",
  "md_casino_client_flag": "1",
  "md_new_IPGEO_city_crc32": "city123",
  "md_suspectCall_date": "2024-01-01",
  "md_userAgent": "Mozilla/5.0",
  "message_CRC32": "msg123",
  "model_phone": "iPhone 13",
  "non_rur_exch": "0",
  "one_month_attribute": "1",
  "p_depEndDate_sys": "2025-12-31",
  "p_dstBankBik": "044525225",
  "p_dstOrganisationID": "123456789",
  "p_prv_grp_id": "1",
  "payCheckResult": "1",
  "pe_actual_residence_place": "Moscow",
  "pe_control_question_flag": "0",
  "pe_deposit_active_flag": "1",
  "pe_inv_value_client": "1000000",
  "pe_vip_flag": "0",
  "pe_vip_flag_2": "0",
  "pe_vip_flag_2_dst": "0",
  "pe_vip_flag_dst": "0",
  "prec_authType_temp": "1",
  "respCq": "0",
  "respSms": "0",
  "ri_dn": "ri123",
  "ri_i160_i177_179_2": "0",
  "risk_mcc": "4814",
  "s_gpu_vendor": "NVIDIA",
  "s_screen_heigth": "1920",
  "s_screen_width": "1080",
  "s_web_user_id_CRC32": "user123",
  "same_currency": "1",
  "same_mn_in_hist_cnt": "1",
  "score": "100",
  "screensharing_flag_dttm": "0",
  "sme_confirmed_device_indicator": "1",
  "sme_orgId_c2c_to_same_recip_200_1d": "0",
  "sme_orgId_norm_200days_to_1acc": "0",
  "sme_organizationId_norm_200days_to_1_INN": "0",
  "sme_organizationId_trxn_200days_to_1acc": "0",
  "sme_trans_dt_week_ago": "2024-01-01",
  "ssoId": "sso123",
  "termType": "1",
  "SystemTime": "2025-10-19T18:42:25.701Z",
  "ukbo_flag": "0",
  "userAgent_md5": "md5hash123",
  "INN_recepient_CRC32": "inn123",
  "s_customer_session_id": "session123",
  "baml": "0",
  "acsMLresult_temp": "1"
}


### Обработка тестового сообщения типа 70
POST http://{{host}}/api/v1/message/70/json
Content-Type: application/json

{
  "paymentId": 1692626,
  "paymentTime": "2025-02-28T06:12:55.052Z",
  "parentPaymentId": 9072957,
  "MessageId": "06d440b273a8598168f6453d",
  "acsURL": "PlRCWVaylachZyjYPsXKsYchAUZ",
  "addInBookDate": "2025-07-26T21:45:35.589Z",
  "agg_submerch": "11111111111111111111",
  "agreement": "EFZvEXUVupSD",
  "Amount_fee": 5142163,
  "amountRub": 8054614,
  "authenticationResult": 7716863,
  "authId": "FJJYqGJSLLqhjnfjLkU",
  "authRc": "BEVYmel",
  "authScheme": "gadRJaD",
  "autopaymentinterface_id": 5745488,
  "bankBik": "11111111111111111111",
  "basicFieldKey": "eM",
  "bnpl_flag": 1000,
  "canvas": "gFqLdGKHLFshhBjRKVkqRPF",
  "cardHolderName": "PNmWlcKnBNpaPOxYfKxzuJHPyTsJsDGxDUSzhoBVaNZacgtVYFphgaQanF",
  "cardNumber": "hVwhgvlUGroqM",
  "cardNumberType": "dHpDwWFeBS",
  "cellularService": 8223535,
  "clientBiometryRes": "Ote",
  "control_question_count": 2279254,
  "cpu": "GGwJszCriUb",
  "cqSupporting": true,
  "currency": "SEOrLYM",
  "currencyFee": 4005101,
  "DE14_exp_date": "JTGlyI",
  "DE22_pos_entry": "hypyCrBCpBniczUYdhQ",
  "DE25_pos_cond": "IBmeedueveFLHDq",
  "DE3_proc_code": "JGai",
  "DE37_RRN": "yQw",
  "DE4_amt_trxn": 5071589,
  "DE43b_merch_city": "gJ",
  "DE49_cur_trxn": "11111111111111111111",
  "DE52_PIN": "GWFkGSezEhTlsSanX",
  "debug_mode_flag": true,
  "deferred": true,
  "depAmount": 4005519,
  "depBik": "IJsUhSUZyGjSshc",
  "depCloseDate": "2025-10-28T14:17:32.416Z",
  "depEndDate": "2025-02-12T00:02:27.453Z",
  "depOpenDate": "2025-10-28T23:41:43.726Z",
  "depReqCancelFlag": "DzrYFiyIrSrCFNTeRGN",
  "deviceId": "vPWuaIIBXaoCnSKTuHvQBxXCCLmoBflEvNGRdMoameN",
  "division": "hQLAIazRkYj",
  "dpan": "LNkYA",
  "dstAgreement": "kRiuWYkrSvdILKcBqAUySyCe",
  "dstCardHash": "DMHoKcoNNLWsBsYvwdymtetkDwLsXV",
  "dstCardNumber": "11111111111111111111",
  "dstCardNumberType": "nrOmZf",
  "dstClientId": "11111111111111111111",
  "earlyCloseDepFlag": 5440394,
  "eci": "jYALSZBafqbUNkED",
  "editTemplateDate": "2025-03-03T06:35:13.300Z",
  "emulator_flag": false,
  "EncashmentType": 1000,
  "EventStage": 3444853,
  "expDate": "ZPuEof",
  "extOperationId": 9663278,
  "family": 3061470,
  "frontCamera": 9374974,
  "fullMerchantName": "CARD2CARD",
  "garmr_id": "SVRUEipBABEheUIz",
  "groupib_pass": 4166606,
  "groupib_score": 5571852,
  "iban": "oorQRoKqLNrWbox",
  "imei": "DSExQCnGMtnqNhZOVejf",
  "inn": "trhvDZttX",
  "inn_sender": "11111111111111111111",
  "innActualPayer": "DfssSTDxHVTxWo",
  "interface": "qWYNmMYNGSHeIUoRbTmf",
  "interface_id": 4022756,
  "invAccountId": 1372917,
  "IP": "AXYzMuVJnSAvxxiPqmHLu",
  "irisId": "aqWftjPEXlNPsZTYyG",
  "lastProlongDate": "2025-07-18T12:56:31.392Z",
  "livenessID": 4492605,
  "livenessScore": 5580103,
  "mainClientId": "RgTRLgbaLh",
  "matchingScore": 2724673,
  "mcc": "EattyXrAKI",
  "merchantId": "LiQWWTNRhpHZNjnIdGRa",
  "merchantName": "eXNvcjPLW",
  "mobile_device_os_version": "ffCuMKxoudVRlQ",
  "msgMode": "odcGVCjCwJYvfpsfmjng",
  "msgStage": 1776118,
  "NFT_to_SME": 8319122,
  "nonResidentSalary": true,
  "notificationURL": "ePCzYSyCxSbsz",
  "NTF_to_SME": 2200752,
  "operationId": 3490941,
  "origin": "wFfyXMndJID",
  "os": "11111111111111111111",
  "OTB_brok": 4797723,
  "payer": "UFECpdjwvrzGzTEVe",
  "pgt_type": "CFbPiyjFjvZu",
  "phone": "nQqKNTrqaDvF",
  "prg_id": 1811321,
  "prv_id": 1000,
  "prvCode": "11111111111111111111",
  "qrId": "XpfjEuEBbdNloKKDBSPUFFdFqlAyGAJWaxCRrxgRcUlFqEpnsycoCQvXLnHJxgUkSSOsMTCipCrjSpIudjhYqSUcBSRVwInIdDdkYXYiKLUmXYMWSDXdKOVFojChXvXqDaUNllVmQvUrsM",
  "qrType": 5199144,
  "receiver_acc_and_bik": "SiTVPEVmuwbp",
  "recipient_name_fl": "fwhVTlouMSEZhkGEfIIlQllPCVfImpZGCCTMaldWOHHZfriurzfatDXGgyfJMjippWcudqifzXWxVOYGJYvyHkByBbUVLKMNDgtlwqTylXEQexCRplLHglKHZvezKqKoOqlJgZbiQytiOBxKALOqDOaUKEROKrlvuvxtsxEFIXPxQEsxRDGlLtTLrsSmDgXfDVuxxUuOAbecKjqpEiwYRuhFNFabUoDlNaiHTulgOPmsFubFUqLlrxqBBmWxXTCmPfIrBttzWxncJMJaRVguPznD",
  "recurringType": "ZnhluCWCdEOtrVtQBjnl",
  "referrer_url": "Czeqzq",
  "requestId": 1000,
  "requireNotify": true,
  "requireQuestionCheck": true,
  "requireSmsOtp": true,
  "resolution": 1,
  "respCode": 1000,
  "respSubCode": 1000,
  "root_flag": false,
  "rules": "11111111111111111111",
  "sbpDeviceModel": "11111111111111111111",
  "score": 2370089,
  "score_rules": "eyOnpzyRloDFIzBxJ",
  "scrCardClientId": "kzvOfEHaxralUOts",
  "screen_height": 9576122,
  "screen_width": 9434155,
  "selfieChallenge": 4211434,
  "servrul": "cIdvgnByrvCdwUrfMgUxgRYiiYUJGKojAaMBDtFkYbDkKeWk",
  "sessionIdAuth": "GWnWGFd",
  "sharingClientID": "zI",
  "sharingDate": "2025-07-16T06:38:45.817Z",
  "siebelUserName": "DkmIdAJzqBGfrCHoRLyH",
  "srcOrganizationId": "11111111111111111111",
  "sso_id": "cpTyxjvL",
  "status": "00",
  "status_reverse": "00",
  "subMerchantId": "FRDzEamAbSxHx",
  "subPrvCode": "nBpAzne",
  "subscriptionId": "CtliSPTCyvUFrkXLJrGiXCQogoJcdSbAQaYY",
  "swift_type": 8770478,
  "SysSrc": 9738558,
  "systemId": 1665750,
  "systemSource": 835459,
  "terminalId": "OJvtQXFevobwbqCpmrE",
  "termType": "11111111111111111111",
  "tinkoffDeviceId": "LimQBN",
  "tracenum": "pCqKDoem",
  "transactionId": "QHFmdxxxnRckEyCEKokofLRcXpnOqKYN",
  "transferType": 7585334,
  "TrxnType": "sdtdmi",
  "ucid": 566521,
  "userAgent": "DjHrXUPfZXrieEFOlRQtbcBLzDQBHdEISeRJmbiHSPsTqlTqQKfDphlapUxKFnvETKTyjRyVihuLnpRsmqsOsysVmIYcytrCbekhtByPKBdWShYGBJJeHwVEtyAnuustlMEPwmifpoIdmaQzoDoPBqIbMAzjsdSPkqJRHFgGqAtYaJTujbpkoaUBXrKkdQ",
  "uuid": "rU",
  "ve_status": "wdEiUnztutOvpFsCcNSx",
  "wuid": "MYSdZIydsqxEQPNYzaQyPtACAkYcVyqcKgUbDAvSek"
}

### Генерация сообщения типа 1
GET http://{{host}}/api/v1/message/1/json

### Генерация сообщения типа 9 (геолокация)
GET http://{{host}}/api/v1/message/9/json

### Генерация сообщения несуществующего типа (должна вернуть 400)
GET http://{{host}}/api/v1/message/999/json

### Генерация сообщения с неверным форматом (должна вернуть 400)
GET http://{{host}}/api/v1/message/abc/json

