#
# Запуск запроса на выполнение Ctrl+Shift+O
# Ctrl+Alt+H
#
@host = localhost:3000
@login = 1
@password = 1

# Тип сообщения
@messageType = 2


### Health check
GET http://{{host}}/health


### Генерация IRIS сообщения типа messageType
# @name newIrisMessage
GET http://{{host}}/api/v1/message/{{messageType}}/iris


### Обработка IRIS XML сообщения
@processedIrisMessage = {{newIrisMessage.response.body.*}}
POST http://{{host}}/api/v1/message/iris
Content-Type: text/xml
Debug-Mode: false

{{processedIrisMessage}}


### Обработка IRIS XML сообщения
POST http://{{host}}/api/v1/message/iris
Content-Type: text/xml
Debug-Mode: false

<IRIS Version="1" Message="ModelRequest" MessageTypeId="50" MessageId="3323123" custom="test">
	<i000>0100</i000>
	<fmt>R</fmt>
	<src>RNP</src>
	<aserno>123123123</aserno>
	<mtrtyp>3</mtrtyp>
	<i003>00</i003>
	<tstamp>2024-12-15 02:59:59</tstamp>
	<i002>22007011111111</i002>
	<SysSrc>15</SysSrc>
	<card_present>false</card_present>
	<i055_offline_sum>0</i055_offline_sum>
	<i055_offline_cnt>0</i055_offline_cnt>
	<i052>N</i052>
	<i006>836.00</i006>
	<eci>N</eci>
	<pinok>0</pinok>
	<no_cvm_vuln>0</no_cvm_vuln>
	<used_signature>0</used_signature>
	<otbAffGrp>7145.28</otbAffGrp>
	<otbAllGrp>7145.28</otbAllGrp>
	<cnt>643</cnt>
	<oac>836.00</oac>
	<agreement>5375191510</agreement>
	<chipTerminal>N</chipTerminal>
	<ssnumber>7-3NEP2IV2J1</ssnumber>
	<mtrspc>0</mtrspc>
	<inn>312329558051</inn>
	<i004>836.00</i004>
	<i011>233423</i011>
	<i014>3401</i014>
	<i018>5814</i018>
	<i022>81</i022>
	<i032>123232</i032>
	<i037>12312312</i037>
	<i041>123123123</i041>
	<i042>12312</i042>
	<i043a>DODO PIZZA test</i043a>
	<i043b>Pizzario, test</i043b>
	<i025>as</i025>
	<cardNumber>2200000000000111111111111111111000</cardNumber>
    <i048>^17280000000000000000000000000000000000000000^320c312329558051^09013</i048>	
	<i049>643</i049>
	<ucid>1121120922</ucid>
    <cd_sign>D</cd_sign>
    <is_financial>Y</is_financial>
    <sme_flag>false</sme_flag>
    <pin_flag>false</pin_flag>
    <token_flag>false</token_flag>
</IRIS>


### Генерация JSON сообщения типа messageType
# @name newMessage
GET http://{{host}}/api/v1/message/{{messageType}}/json

### Обработка сообщения типа messageType
@processedMessage = {{newMessage.response.body.$}}
POST http://{{host}}/api/v1/message/{{messageType}}/json
Content-Type: application/json
Debug-Mode: false

{{processedMessage}}


### Обработка тестового сообщения типа messageType
POST http://{{host}}/api/v1/message/{{messageType}}/json
Content-Type: application/json
Debug-Mode: true

{
  "id": "2bc902747112fdf768e81748",
  "messageTypeId": {{messageType}},
  "amount": 3113715,
  "dt": "2025-06-10T13:12:31.695Z",
  "f1": "1234567890",
  "f2": "value1",
  "f3": 2,
  "f4": "1234567890",
  "f5": "1234567890",
  "f6": "1234567890",
  "f12": "1234567890",
  "f20": "1234567890",
  "f21": "1234567890",
  "f22": "1234567890"
}


### Обработка сообщения типа 1
POST http://{{host}}/api/v1/message/1/json
Content-Type: application/json

{
    "MessageId": "1e2f63841e9fbea668e68832",
    "acc_identification_flag": 1000,
    "acc_prepaid": false,
    "agreement": 1000,
    "custom_auth_limit": 1000,
    "dst_client_id": "ZQhYClA",
    "fid_md": 1000,
    "from_ros": 8579521,
    "grade": 92791,
    "inn": "PbpMhelLISNEv",
    "INN_recepient": "AufzrzfAwc",
    "insurance_activity": 9336780,
    "ip_address": "AWbCdqHJZFj",
    "kir_flg": 1000,
    "md_agreement_rosbank_flag": 5784330,
    "md_fid01": 1000,
    "md_fid01.2": 1504285,
    "md_fid02": 5760850,
    "md_fid02.2": 2202780,
    "md_fid03": 7484933,
    "md_fid04": 8633290,
    "md_fid08.1": 2025269,
    "md_fid08.2": 1000,
    "md_fid08.3": 9591313,
    "md_fid09": 1007326,
    "md_fid10": 3745525,
    "md_fid11": 3053738,
    "md_fid15": 986823,
    "md_fid15.2": 3947106,
    "md_fid16": 3878886,
    "md_fid16.2": 7593227,
    "md_rosbank_userAgent": "11111111111111111111",
    "monthly_limit": 1126849,
    "msgMode": "BygSfxSuugyBocfX",
    "organization_id": "OhWVZYyyPRF",
    "p_dstCardNumber": "HJv",
    "p_dstClientId": "fyotHYtGHFYfEhUqHIHBwZ",
    "p_dstOrganisationID": "YqybHOxIhzIRfpqbk",
    "pan": "ApaxoNCp",
    "PAN": "APxmCkSAGgLz",
    "pe_aml_status": 4801163,
    "pe_birthdate_dst": "2024-10-10T11:35:40.753Z",
    "pe_child_flag": 3823825,
    "pe_drop_flag": 8423561,
    "pe_dst_aml_status": 1978279,
    "pe_parent_flag": 3616571,
    "pe_phone_dst": "kNEmy",
    "pe_pm_client_id": "aHOjhGmYOVv",
    "pe_pm_flag_num": 4287917,
    "pe_rosbank_private_flag": 5292035,
    "pe_vip_flag_2_phone": 7153399,
    "ph_segment": 4078799,
    "phone": "dOgIp",
    "receiver_acc_and_bik": "bijyty",
    "rosbank_risk_flag1": 4914738,
    "rosbank_risk_flag2": 8833656,
    "rosbank_risk_flag3": 52819,
    "s_client_id": "eFxpEYeilSTZtjWEk",
    "s_organization_id": "FkRFJIAElZlyw",
    "subscription": 5095931,
    "subscription_date": "2024-07-22T06:20:28.636Z",
    "sum_credlimit": 6760985,
    "timestamp": "2024-09-26T14:18:25.203Z",
    "vul_flg": true
}

### Генерация сообщения типа 1
GET http://{{host}}/api/v1/message/1/json

### Генерация сообщения типа 9 (геолокация)
GET http://{{host}}/api/v1/message/9/json

### Генерация сообщения несуществующего типа (должна вернуть 400)
GET http://{{host}}/api/v1/message/999/json

### Генерация сообщения с неверным форматом (должна вернуть 400)
GET http://{{host}}/api/v1/message/abc/json

